apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 4
  selector:
    matchLabels:  
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
  spec:
    containers:
    - name: python-flask-app
      image : akanshachauhary/python-flask-app:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
      - containerPort: 5000
      
